### ISSUE TITLE
Script causing twitter pages to break

### ISSUE THREAD

**Issue by SilentSparrow02** [flyhaozi/NSFW-Expander-for-Twitter#4]
Every profile I try to view shows a "X hasn't tweeted" message ([example](https://i.imgur.com/o5QmoWA.png)). Page loads normally with script turned off. Could you please fix it? Thank you

**Comment by Pancakes0** [comment]
yeah i dont think it works anymore, twitter probably updated their censoring, because this worked a few months back if recall correctly....

**Comment by yuhaofe** [comment]
Sorry for late response, Twitter no longer returns all sensitive tweets to non-logged in users, this script doesn't work anymore.

**Comment by SilentSparrow02** [comment]
Sad :(
Thanks anyway!
